name: SCCNcraft
version: 1.0
main: in.shaycryptoco.SCCNcraft.Main
api-version: 1.16
commands:
  balance:
    description: Check a user's SCCN balance
    aliases: bal
  eco:
    description: Edit user SCCN balances
  pay:
    description: Pay SCCN to users
  rules:
    description: Check the server rules
  help:
    description: View more information
  playtime:
    description: View user playtime