name: SCCNcraft
version: 1.0
main: in.shaycryptoco.SCCNcraft.Main
api-version: 1.16
commands:
  bal:
    description: Check a user's SCCN balance
  balance:
    description: Check a user's SCCN balance
  eco:
    description: Check a user's SCCN balance
  pay:
    description: Pay [user] [amount] SCCN